name: Deploy to My Server

on:
  push:
    branches:
      - main   # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
            sudo apt-get install -y sshpass
            sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "/opt/scripts/deploy.sh"
